version: '3'

services:
  api:
    image: node:14-alpine
    command: npm run dev
    working_dir: /root/app
    environment:
      NODE_ENV: development
      PORT: 8080
      HOST: 0.0.0.0
      APP_KEY: QRVrjkf0dhZ-uiJV5pDfAb60oYgfKAF
    ports:
      - 8080:8080
    volumes:
      - .:/root/app

  localstack:
    image: localstack/localstack
    environment:
      SERVICES: dynamodb
      DATA_DIR: /tmp/localstack/data
    ports:
      - 4566:4566
    volumes:
      - localstack-data:/tmp/localstack/data
      - /var/run/docker.sock:/var/run/docker.sock

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    environment:
      DYNAMO_ENDPOINT: 'http://localstack:4566'
    ports:
      - 8001:8001

volumes:
  localstack-data:
